import types
from typing import Any, Protocol, Self


class Reporter(Protocol):
    def add_task(
        self, description: str, total: float | None = 0, **fields: Any
    ) -> Any: ...
    def update_task(self, task_id: Any, **fields: Any) -> None: ...
    def remove_task(self, task_id: Any) -> None: ...
    def info(self, msg: str, *args: Any) -> None: ...
    def warning(self, msg: str, *args: Any) -> None: ...
    def error(self, msg: str, *args: Any) -> None: ...
    def success(self, msg: str, *args: Any) -> None: ...
    def on_live_update(self, size: str, speed: str) -> None: ...
    def ask_retry(self) -> bool: ...

    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: types.TracebackType | None,
    ) -> None: ...
